services:
  postgres:
    image: postgres:17.1
    container_name: employee-management
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: management_db
    ports:
      - "5432:5432"
